// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddBird(arg1) {
  return window['go']['main']['App']['AddBird'](arg1);
}

export function GetLifelist() {
  return window['go']['main']['App']['GetLifelist']();
}

export function GetLocations() {
  return window['go']['main']['App']['GetLocations']();
}

export function GetUserText(arg1) {
  return window['go']['main']['App']['GetUserText'](arg1);
}

export function ImportLifelist() {
  return window['go']['main']['App']['ImportLifelist']();
}

export function IsReady() {
  return window['go']['main']['App']['IsReady']();
}

export function SearchBirds(arg1) {
  return window['go']['main']['App']['SearchBirds'](arg1);
}
