// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {internal} from '../models';
import {maps} from '../models';

export function AddBird(arg1:internal.Bird):Promise<void>;

export function GetLifelist():Promise<Array<internal.Bird>>;

export function GetLocations():Promise<Array<maps.Location>>;

export function GetUserText(arg1:string):Promise<void>;

export function ImportLifelist():Promise<void>;

export function IsReady():Promise<boolean>;

export function SearchBirds(arg1:string):Promise<Array<internal.Bird>>;
